### ISSUE TITLE
About Inter-task Transferability

### ISSUE THREAD

**Issue by chakkritte** [EMI-Group/RelativeNAS#1]
Hi @tanhao1998, @ShihuaHuang95, @EMI-Group ,

Thanks for sharing your code. 

Could you release the source code of Inter-task Transferability such as object detection?

Many Thanks.

**Comment by ShihuaHuang95** [comment]
@chakkritte Thanks for your interest in our work. And yes, we will release those implementations recently. Please cite our work if it helps your research.

**Comment by ShihuaHuang95** [comment]
@chakkritte We have released the implementation of those tasks, dubbed TrasferLearning-Tasks, please enjoy it. Many thanks again for your interest.

**Comment by chakkritte** [comment]
Hi @ShihuaHuang95,

Thank you so much for your work.

Yes, I will cite your paper.
